inherit_from: rubocop-todo.yml

# Rubocop complains about names that begin with set_ and get_.
AccessorMethodName:
  Exclude:
    - lib/rpicsim/mplab/**

# Rubocop disagrees with lines like:
#   @sfrs[name] or raise 'SFR not found.'
AndOr:
  Enabled: false

# Rubocop wants to us to specify the encoding at the top of
# every single source file if RUBY_VERSION < '2.0.0'.
Encoding:
  Enabled: false

# This cop was present in rubocop 0.18.1.
# Later versions should have a StringFormat cop that we can
# configure to say that we prefer using the String#% operator.
FavorSprintf:
  Enabled: false

# We use 'if false' to disable a spec that is actually supposed to raise an
# error, which is just there to help us write the documentation.
LiteralInCondition:
  Exclude:
    - spec/example/nice_error_spec.rb

SignalException:
  EnforcedStyle: only_raise

# We disable the TrailingComma cop because depending on how we configure it,
# it will do one of the following undesirable things:
# - Require us to put commas at the end of parameter lists for multi-line
#   method calls.
# - Require us to remove commas at the end of multi-line arrays and hashes.
TrailingComma:
  Enabled: false
  EnforcedStyleForMultiline: comma

# Rubcop was complaining about accessors being trivial even if they had a
# different name than the instance variable they access.
TrivialAccessors:
  ExactNameMatch: true

# Rubocop thinks we should always be using %w for arrays of words.
WordArray:
  Enabled: false

