inherit_from: rubocop-todo.yml

# Rubocop thinks we should always be using %w for arrays of words.
WordArray:
  Enabled: false

# Rubcop was complaining about accessors being trivial even if they had a
# different name than the instance variable they access.
TrivialAccessors:
  ExactNameMatch: true

# We disable the TrailingComma cop because depending on how we configure it,
# it will do one of the following undesirable things:
# - Require us to put commas at the end of parameter lists for multi-line
#   method calls.
# - Require us to remove commas at the end of multi-line arrays and hashes.
TrailingComma:
  Enabled: false
  EnforcedStyleForMultiline: comma